/**
 * Vitest stand-in for wasm `looks_like_tailwind_utility`.
 * Source of truth: `crates/tailwind-atomic/src/tailwind.rs`.
 */
const BARE = new Set([
	"absolute",
	"antialiased",
	"block",
	"blur",
	"border",
	"capitalize",
	"collapse",
	"container",
	"contents",
	"filter",
	"fixed",
	"flex",
	"grayscale",
	"grid",
	"group",
	"grow",
	"hidden",
	"inline",
	"invert",
	"invisible",
	"isolate",
	"italic",
	"lowercase",
	"ordinal",
	"outline",
	"overline",
	"peer",
	"prose",
	"relative",
	"resize",
	"ring",
	"sepia",
	"shadow",
	"shrink",
	"static",
	"sticky",
	"table",
	"transform",
	"transition",
	"truncate",
	"underline",
	"uppercase",
	"visible",
]);

const EXACT = new Set([
	"border-collapse",
	"border-separate",
	"box-border",
	"box-content",
	"break-all",
	"break-keep",
	"break-normal",
	"break-words",
	"caption-bottom",
	"caption-top",
	"decoration-clone",
	"decoration-slice",
	"diagonal-fractions",
	"drop-shadow",
	"flow-root",
	"inline-block",
	"inline-flex",
	"inline-grid",
	"inline-table",
	"line-through",
	"lining-nums",
	"list-item",
	"no-underline",
	"normal-case",
	"normal-nums",
	"not-italic",
	"not-sr-only",
	"oldstyle-nums",
	"overflow-ellipsis",
	"proportional-nums",
	"ring-inset",
	"scroll-auto",
	"scroll-smooth",
	"slashed-zero",
	"sr-only",
	"stacked-fractions",
	"subpixel-antialiased",
	"table-auto",
	"table-fixed",
	"tabular-nums",
	"text-balance",
	"text-nowrap",
	"text-pretty",
	"text-wrap",
]);

const PREFIXES = [
	"accent-",
	"align-",
	"animate-",
	"appearance-",
	"aspect-",
	"auto-cols-",
	"auto-rows-",
	"backdrop-blur-",
	"backdrop-brightness-",
	"backdrop-contrast-",
	"backdrop-grayscale-",
	"backdrop-hue-rotate-",
	"backdrop-invert-",
	"backdrop-opacity-",
	"backdrop-saturate-",
	"backdrop-sepia-",
	"backdrop-",
	"backface-",
	"basis-",
	"bg-blend-",
	"bg-conic-",
	"bg-gradient-",
	"bg-linear-",
	"bg-radial-",
	"bg-",
	"blur-",
	"border-spacing-",
	"border-x-",
	"border-y-",
	"border-s-",
	"border-e-",
	"border-t-",
	"border-r-",
	"border-b-",
	"border-l-",
	"border-",
	"bottom-",
	"box-decoration-",
	"box-",
	"break-after-",
	"break-before-",
	"break-inside-",
	"break-",
	"brightness-",
	"caption-",
	"caret-",
	"clear-",
	"col-end-",
	"col-span-",
	"col-start-",
	"col-",
	"columns-",
	"content-",
	"contrast-",
	"cursor-",
	"decoration-",
	"delay-",
	"divide-x-",
	"divide-y-",
	"divide-",
	"drop-shadow-",
	"duration-",
	"ease-",
	"end-",
	"field-sizing-",
	"fill-",
	"flex-",
	"float-",
	"font-",
	"forced-color-adjust-",
	"from-",
	"gap-x-",
	"gap-y-",
	"gap-",
	"grayscale-",
	"grid-cols-",
	"grid-flow-",
	"grid-rows-",
	"grow-",
	"h-",
	"hue-rotate-",
	"hyphens-",
	"indent-",
	"inline-",
	"inset-ring-",
	"inset-shadow-",
	"inset-x-",
	"inset-y-",
	"inset-",
	"invert-",
	"items-",
	"justify-items-",
	"justify-self-",
	"justify-",
	"leading-",
	"left-",
	"line-clamp-",
	"list-image-",
	"list-",
	"m-",
	"mask-",
	"max-h-",
	"max-w-",
	"max-",
	"mb-",
	"me-",
	"min-h-",
	"min-w-",
	"min-",
	"mix-blend-",
	"ml-",
	"mr-",
	"ms-",
	"mt-",
	"mx-",
	"my-",
	"object-",
	"opacity-",
	"order-",
	"origin-",
	"outline-offset-",
	"outline-",
	"overflow-x-",
	"overflow-y-",
	"overflow-",
	"overscroll-x-",
	"overscroll-y-",
	"overscroll-",
	"p-",
	"pb-",
	"pe-",
	"perspective-",
	"place-content-",
	"place-items-",
	"place-self-",
	"place-",
	"placeholder-",
	"pl-",
	"pointer-events-",
	"pr-",
	"prose-",
	"ps-",
	"pt-",
	"px-",
	"py-",
	"resize-",
	"right-",
	"ring-offset-",
	"ring-",
	"rotate-x-",
	"rotate-y-",
	"rotate-z-",
	"rotate-",
	"rounded-ss-",
	"rounded-se-",
	"rounded-ee-",
	"rounded-es-",
	"rounded-tl-",
	"rounded-tr-",
	"rounded-br-",
	"rounded-bl-",
	"rounded-s-",
	"rounded-e-",
	"rounded-t-",
	"rounded-r-",
	"rounded-b-",
	"rounded-l-",
	"rounded-",
	"row-end-",
	"row-span-",
	"row-start-",
	"row-",
	"saturate-",
	"scale-x-",
	"scale-y-",
	"scale-z-",
	"scale-",
	"scheme-",
	"scroll-m-",
	"scroll-p-",
	"scroll-px-",
	"scroll-py-",
	"scroll-ps-",
	"scroll-pe-",
	"scroll-pt-",
	"scroll-pr-",
	"scroll-pb-",
	"scroll-pl-",
	"scroll-mx-",
	"scroll-my-",
	"scroll-ms-",
	"scroll-me-",
	"scroll-mt-",
	"scroll-mr-",
	"scroll-mb-",
	"scroll-ml-",
	"scroll-",
	"select-",
	"self-",
	"sepia-",
	"shadow-",
	"shrink-",
	"size-",
	"skew-x-",
	"skew-y-",
	"skew-",
	"snap-",
	"space-x-",
	"space-y-",
	"space-",
	"sr-",
	"start-",
	"stroke-",
	"table-",
	"text-shadow-",
	"text-",
	"to-",
	"top-",
	"touch-",
	"tracking-",
	"transform-",
	"transition-",
	"translate-x-",
	"translate-y-",
	"translate-z-",
	"translate-",
	"underline-offset-",
	"via-",
	"w-",
	"whitespace-",
	"will-change-",
	"z-",
];

function unescapeCssClassName(value: string) {
	return value
		.replace(/\\([^\n\r\f0-9a-fA-F])/g, "$1")
		.replace(/\\([0-9a-fA-F]{1,6})[ \t\n\r\f]?/g, (_, hex: string) => {
			const code = Number.parseInt(hex, 16);
			return Number.isFinite(code) ? String.fromCodePoint(code) : "";
		});
}

function variantColonIndex(name: string) {
	let depth = 0;
	for (let i = 0; i < name.length; i++) {
		const ch = name[i];
		if (ch === "\\") {
			i += 1;
			continue;
		}
		if (ch === "[") depth += 1;
		else if (ch === "]" && depth > 0) depth -= 1;
		else if (ch === ":" && depth === 0) return i;
	}
	return -1;
}

function coreUtilityName(name: string) {
	let rest = name;
	for (;;) {
		if (rest.startsWith("!")) rest = rest.slice(1);
		const colon = variantColonIndex(rest);
		if (colon < 0) break;
		rest = rest.slice(colon + 1);
	}
	return rest.startsWith("!") ? rest.slice(1) : rest;
}

export function looksLikeTailwindUtility(className: string) {
	const name = unescapeCssClassName(className);
	if (!name) return false;
	const core = coreUtilityName(name);
	if (!core) return false;
	if (core.includes("[")) return true;
	const unsigned = core.startsWith("-") ? core.slice(1) : core;
	const base = unsigned.split("/")[0] ?? unsigned;
	if (BARE.has(base) || EXACT.has(base)) return true;
	return PREFIXES.some((prefix) => base.startsWith(prefix) && base.length > prefix.length);
}
